# Generated by Django 3.0.2 on 2020-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='specific',
            field=models.TextField(default='Testing'),
            preserve_default=False,
        ),
    ]
