# Generated by Django 3.0.2 on 2020-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
